---

- name: establish dependencies
  become: yes 
  package:
    name: npm
    state: present
  tags: install

- name: establish cerebro
  become: yes
  apt:
    deb: https://github.com/KELiON/cerebro/releases/download/v0.3.2/cerebro_0.3.2_amd64.deb
  tags: install

- name: ensure config directory presence
  file:
    path: "{{ config_path[ansible_system] }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "ug=rwx,o=r"
    state: directory
  loop:
    - ""
    - "plugins"
  tags: install
  
- name: establish plugins
  shell: npm install --save cerebro-{{ item }} {{ '--proxy %s' | format(environment["http_proxy"]) if environment and 'http_proxy' in environment else '' }}
  args:
    chdir: "{{ config_path[ansible_system] }}/plugins/" 
  loop: "{{ plugins }}"
  tags: install

- name: establish configuration
  template:
    src: config.json.j2
    dest: "{{ config_path[ansible_system] }}/config.json"
  tags: configure

