---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: true

    - name: Ubuntu | add universe repo
      when: ansible_distribution == 'Ubuntu'
      become: true
      apt_repository:
        repo: "deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} universe"
        filename: universe
        state: present

  roles:
    - role: ansible-role-cerebro
      vars:
        cerebro_configuration:
          hotkey: "Control+Shift+Space"
        cerebro_plugins:
          - basic-apps
